# Generated by Django 5.0.2 on 2024-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profiles_email_remove_profiles_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], default='', max_length=50),
        ),
    ]
