# Generated by Django 5.0.3 on 2024-03-06 13:27

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='strt_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='initial_deposit',
            field=models.DecimalField(decimal_places=2, default='', max_digits=15),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkbook.account')),
            ],
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
    ]
