# Generated by Django 5.0.3 on 2024-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_rename_fname_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initial_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
